### ISSUE TITLE
Thoughts

### ISSUE THREAD

**Issue by thebrianbug** [markjaquith/clerk-sveltekit#9]
A random assortment of crazy ideas looking through the repo

- Wow, you did really well with making the components 👏! Sweet!
- Why is there a `bun.lockb` file, and an `.npmrc`? What package manager is preferred for the project?
- I like to have an `example.env` file for easy copy-paste to get started. Can we create one?

All in all, it seems to work so I'll be experimenting with it in my project and letting you know how it goes 🤞

**Comment by markjaquith** [comment]
I used bun as the package manager. `.npmrc` is leftover boilerplate so that can be deleted.

`.env.example` is a great pattern, agree.

I want to improve how the login flow stuff works. The cookie checking is crude and unreliable.

Also, we need a way to do session revalidation without booting the user away from a protected endpoint. Maybe by detecting an expired session and booting them back to login with the afterSignInUrl set.

**Comment by thebrianbug** [comment]
A new release is ready to go with nothing but fixing broken docs. Feel free to adjust or upload binaries. IDK how to do that and I don't want to screw something up @markjaquith

**Comment by markjaquith** [comment]
On it!

So the way that releases are handled is the same way that SvelteKit does it... with the [changesets](https://github.com/changesets/changesets) package and actions.

Basically, after a meaningful change, you run `bun changset` and indicate what kind of change it is. It'll write that changeset with a random name, and you commit it. When when there are unreleased changesets, the GitHub Actions bot will open a PR. If you merge that PR, it'll release it to NPM, deleting the changesets, merging them into the changelog, all that good stuff. It's a really easy workflow.
